name: Repomix Summary Update

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'llm_context.md'
  workflow_dispatch:

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install repomix
        run: pip install repomix

      - name: Run repomix
        run: repomix summarize --output llm_context.md

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add llm_context.md
          if ! git diff --cached --quiet; then
            git commit -m "Update llm_context.md via repomix [skip ci]"
            git push
          fi
