name: Repomix Summary Update

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'llm_context.md'
  workflow_dispatch:

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or another version if you prefer

      - name: Run repomix
        run: |
          npx repomix --compress --style markdown \
            --no-file-summary --no-directory-structure \
            --include "*.md,**/*.md" \
            --ignore CHANGELOG.md,CONTRIBUTING.md,.github/** \
            --output llm_context.md

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add llm_context.md
          if ! git diff --cached --quiet; then
            git commit -m "Update llm_context.md via repomix [skip ci]"
            git push
          fi
